# Generated by Django 3.2.25 on 2024-03-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
