# Generated by Django 3.2.25 on 2024-03-25 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0002_portfolio_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='bank_name',
            new_name='account_name',
        ),
    ]
