# Generated by Django 3.2.25 on 2024-03-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0003_rename_bank_name_transactions_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='amount_used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='transaction_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
