# Generated by Django 3.2.25 on 2024-04-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0005_transactions_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingtransaction',
            name='shopitem',
        ),
        migrations.RemoveField(
            model_name='shoppingtransaction',
            name='username',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='account_number',
        ),
        migrations.AddField(
            model_name='transactions',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
        migrations.DeleteModel(
            name='ShoppingTransaction',
        ),
    ]
