# Generated by Django 3.2.25 on 2024-04-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0006_auto_20240401_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='bank_swift_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='beneficiary_phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
