# Generated by Django 3.2.25 on 2024-09-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0008_auto_20240607_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='checkings',
            new_name='account_number',
        ),
    ]
