# Generated by Django 5.1.1 on 2024-09-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0009_rename_checkings_portfolio_account_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='beneficiary_phone_number',
            new_name='account_number',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='loan_balance',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='account_name',
        ),
        migrations.AddField(
            model_name='transactions',
            name='sender_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
