# Generated by Django 5.1.1 on 2024-09-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0010_rename_beneficiary_phone_number_transactions_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
