# Generated by Django 5.1.1 on 2024-09-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0012_rename_account_number_transactions_beneficiary_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
