# Generated by Django 5.1.1 on 2024-09-10 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0013_alter_transactions_account_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='account_name',
        ),
    ]
