# Generated by Django 5.1.1 on 2024-09-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0014_remove_transactions_account_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='amount_used',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='transaction_category',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='account_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='bank_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='beneficiary_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='beneficiary_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='branch_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
