# Generated by Django 5.1.1 on 2024-09-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0015_remove_transactions_amount_used_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='beneficiary_phone_number',
            new_name='senders_phone_number',
        ),
        migrations.AddField(
            model_name='transactions',
            name='account_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
