# Generated by Django 5.1.1 on 2024-09-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0017_alter_transactions_senders_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
