# Generated by Django 5.1.1 on 2024-09-11 14:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0021_alter_portfolio_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
