# Generated by Django 4.2.16 on 2024-10-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0023_portfolio_amount_sign_transactions_amount_sign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='amount_sign',
            field=models.CharField(blank=True, choices=[('$', 'Dollar'), ('£', 'Pound Sterling'), ('€', 'Euro'), ('₣', 'Swiss Franc'), ('kr', 'Danish Krone'), ('kr', 'Swedish Krona'), ('kr', 'Norwegian Krone'), ('zł', 'Polish Zloty'), ('₴', 'Ukrainian Hryvnia'), ('лв', 'Bulgarian Lev'), ('Ft', 'Hungarian Forint'), ('lei', 'Romanian Leu'), ('₺', 'Turkish Lira'), ('руб', 'Russian Ruble'), ('Kč', 'Czech Koruna'), ('kn', 'Croatian Kuna'), ('RSD', 'Serbian Dinar'), ('MKD', 'Macedonian Denar'), ('ISK', 'Icelandic Krona')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount_sign',
            field=models.CharField(blank=True, choices=[('$', 'Dollar'), ('£', 'Pound Sterling'), ('€', 'Euro'), ('₣', 'Swiss Franc'), ('kr', 'Danish Krone'), ('kr', 'Swedish Krona'), ('kr', 'Norwegian Krone'), ('zł', 'Polish Zloty'), ('₴', 'Ukrainian Hryvnia'), ('лв', 'Bulgarian Lev'), ('Ft', 'Hungarian Forint'), ('lei', 'Romanian Leu'), ('₺', 'Turkish Lira'), ('руб', 'Russian Ruble'), ('Kč', 'Czech Koruna'), ('kn', 'Croatian Kuna'), ('RSD', 'Serbian Dinar'), ('MKD', 'Macedonian Denar'), ('ISK', 'Icelandic Krona')], max_length=5, null=True),
        ),
    ]
